CREATE TABLE IF NOT EXISTS users (
 id BIGSERIAL PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(254) NOT NULL UNIQUE,
 password_hash TEXT NOT NULL,
 role VARCHAR(10) NOT NULL CHECK(role IN ('ADMIN','USER')) DEFAULT 'USER',
 avatar_url TEXT,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS products (
 id BIGSERIAL PRIMARY KEY,
 name VARCHAR(150) NOT NULL,
 category VARCHAR(80) NOT NULL DEFAULT 'Digital',
 price_cents BIGINT NOT NULL DEFAULT 0 CHECK(price_cents>=0),
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS customers (
 id BIGSERIAL PRIMARY KEY,
 name VARCHAR(150) NOT NULL,
 email VARCHAR(254),
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS sales (
 id BIGSERIAL PRIMARY KEY,
 customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
 product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
 amount_cents BIGINT NOT NULL CHECK(amount_cents>=0),
 status VARCHAR(12) NOT NULL CHECK(status IN ('PAID','PENDING','CANCELLED')),
 sold_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS password_resets (
 id BIGSERIAL PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 token_hash CHAR(64) NOT NULL UNIQUE,
 expires_at TIMESTAMPTZ NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sales_sold_at ON sales(sold_at);
CREATE INDEX IF NOT EXISTS idx_sales_status ON sales(status);
CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email);
CREATE INDEX IF NOT EXISTS idx_password_resets_expires ON password_resets(expires_at);
